Fix orphaned sleeps and ignored pkill error 1
- Using exec sleep instead of simply sleep means that sleep processes
run as children of the invoking one. Therefore they die with it and
don't remain around as orphaned processes.
- pkill returns 1 if there is nothing to kill; this is fine (it means
there were no redis-server in the first place) so we ignore
that exit code in the process destroyer stop script. Any other non-zero
exit code from pkill will cause the stop script to fail.

[#137029011]

Signed-off-by: Maria Ntalla <mntalla@pivotal.io>

diff --git a/jobs/cf-redis-broker/templates/process-destroyer_ctl.erb b/jobs/cf-redis-broker/templates/process-destroyer_ctl.erb
--- a/jobs/cf-redis-broker/templates/process-destroyer_ctl.erb
+++ b/jobs/cf-redis-broker/templates/process-destroyer_ctl.erb
@@ -8,11 +8,18 @@ case $1 in
 
   start)
     echo $$ > $PIDFILE
-    while true; do sleep 10000; done
+    while true; do exec sleep 10000; done
     ;;
 
   stop)
-    pkill redis-server || true
+    set +e
+      pkill redis-server
+      pkillExitCode=$?
+    set -e
+    # exit code 1 = nothing to kill, which is OK
+    if [ "${pkillExitCode}" -gt 1 ]; then
+      exit $pkillExitCode
+    fi
     kill_and_wait $PIDFILE 55
     ;;
 
