Make start script skip thp disabled on bosh-lite
- bosh-lite is a read-only file system

[#157603694]

Signed-off-by: Sarah Connor <sconnor@pivotal.io>

diff --git a/jobs/dedicated-node/templates/start.erb b/jobs/dedicated-node/templates/start.erb
--- a/jobs/dedicated-node/templates/start.erb
+++ b/jobs/dedicated-node/templates/start.erb
@@ -23,7 +23,10 @@ rm -f $DATA_DIR/temp-*.rdb
 ulimit -n 10032
 
 if test -f /sys/kernel/mm/transparent_hugepage/enabled; then
+  # fail silently as bosh-lite is a read-only file system
+  set +e
   echo never > /sys/kernel/mm/transparent_hugepage/enabled
+  set -e
 fi
 
 sysctl -w net.core.somaxconn=511
